sudo: required

services:
  - docker

before_install:
  - docker build -t yanness687/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yanness687/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-frontend"
  env: "React-frontend-end"
  bucket_name: "elasticbeanstalk-us-east-2-329599627386"
  bucket_path: "react-frontend" # by default, use your app name as the "bucket_path"
  on:
    branch: master
  access_key_id: $Access key (AWS)
  secret_access_key: "$Secret access key"